package com.blogspot.fravalle.data.orm.derby.cayenne.iw3d.auto;

import org.apache.cayenne.ObjectContext;

/**
 * This class was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public class _Datamap_iw3d {
}